### PR TITLE
new Netatmo-API

### PR DESCRIPTION
**Pull request by JurgenLB**
I dit a rewrite off my code.
Maybe you can test this.
With my setup the devices are working with multiple homes in my account.

I also dit a complete new install from the latest beta source including your authentication changes 
with this setup I can't make the login work.

image

Kind regards

### CODE REVIEW

**Comment by JurgenLB** [comment]
can it be that the following is inverted;
`
                                                        var href = $("#updelclr #hardwareupdate").attr("href");
                                                        if (typeof href == 'undefined') {
                                                                AddHardware (); //Is Selected device, update
                                                        }
                                                        else
                                                                UpdateHardware (idx, 0, 0, 0, 0, 0, 0); //Is not a selected device. so must be new
`
When selected there is 'AddHardware' else there is UpdateHardware.

Kind regards

**Comment by LoukKamp** [comment]
```
                                                        var href = $("#updelclr #hardwareupdate").attr("href");
                                                        if (typeof href == 'undefined') {
                                                                AddHardware (); //Is Selected device, update
                                                        }
                                                        else
                                                                UpdateHardware (idx, 0, 0, 0, 0, 0, 0); //Is not a selected device. so must be new

```
No, the code first reads the href attribute from the table row: If the attribute is not defined (was not present), then this means that the table row was not selected, so It should add the device as a new device.

However, good that you mentioned this, because I realized that this contains dead code: Because now, the login button is disabled when there is no row selected, so the first case in the if-statement will never be executed and can be removed.

I changed this (disabling the login button), because I could not guaranty that all data is consistent, when the user presses the login button when the row is not selected, and may contain old data.

**Comment by LoukKamp** [comment]
Are you sure, the camera scope is for indoor camera's only?

**Comment by LoukKamp** [comment]
OK, maybe you're right:

afbeelding

**Comment by JurgenLB** [comment]
Yes the 'camera' scope is for the indoor camera.
There is also a possibility to extend the indoor camera with 'Doortags' and they use the same scope
because the indoor camera is the bridge for the tags.

So the naming can be just 'Indoor camera'

For Gismocuz I dit make some changing .

**Comment by JurgenLB** [comment]
> ```
>         var href = $("#updelclr #hardwareupdate").attr("href");
>         if (typeof href == 'undefined') {
>                 AddHardware (); //Is Selected device, update
>         }
>         else
>                 UpdateHardware (idx, 0, 0, 0, 0, 0, 0); //Is not a selected device. so must be new
> ```
> 
> No, the code first reads the href attribute from the table row: If the attribute is not defined (was not present), then this means that the table row was not selected, so It should add the device as a new device.
> 
> However, good that you mentioned this, because I realized that this contains dead code: Because now, the login button is disabled when there is no row selected, so the first case in the if-statement will never be executed and can be removed.
> 
> I changed this (disabling the login button), because I could not guaranty that all data is consistent, when the user presses the login button when the row is not selected, and may contain old data.

I find your comment behind the line in the code with your explanation very confusing.
But I understand that this is going to be changed

Kind regards

**Comment by LoukKamp** [comment]
Ah, now I see what you mean: I've only looked at the code, never read the comments :shame:

I'll take it out.

**Comment by LoukKamp** [comment]
After resetting/syncing to the current beta, I merged your changes into my working tree and was a bit disappointed: No change in the huge battery levels.... But I assume that is not handled by the Netatmo.cpp module in the hardware folder (the only significant changes in this commit); You probably forgot to add the other changed module in this commit?

However, after checking the logs, I found the following:

```
2024-09-01 03:15:46.720 Status: NetAtmoWeerEnLuchtkwaliteit: Use refresh token from database...
2024-09-01 03:15:46.720 Status: NetAtmoWeerEnLuchtkwaliteit: Requesting refreshed tokens
2024-09-01 03:20:16.952 Status: NetAtmoWeerEnLuchtkwaliteit: Get HomesData Details
2024-09-01 03:20:17.194 Status: NetAtmoWeerEnLuchtkwaliteit: Home id WeerStation Oost-Graftdijk updated.
2024-09-01 03:20:17.449 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Binnen] no longer updated (module possibly disconnected)
2024-09-01 03:20:17.449 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Regenmeter] no longer updated (module possibly disconnected)
2024-09-01 03:20:17.449 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Slaapkamer Oostzijde] no longer updated (module possibly disconnected)
2024-09-01 03:20:17.449 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Buiten - oost] no longer updated (module possibly disconnected)
2024-09-01 03:20:17.449 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Eetkamer/Keuken] no longer updated (module possibly disconnected)
2024-09-01 03:20:17.449 Status: NetAtmoWeerEnLuchtkwaliteit: HomeStatus parsed
2024-09-01 03:20:17.670 Status: NetAtmoWeerEnLuchtkwaliteit: Events Data parsed
2024-09-01 03:20:17.670 Status: NetAtmoWeerEnLuchtkwaliteit: Status 1

2024-09-01 03:35:17.750 Status: NetAtmoWeerEnLuchtkwaliteit: Get HomesData Details
2024-09-01 03:35:18.036 Status: NetAtmoWeerEnLuchtkwaliteit: Home id WeerStation Oost-Graftdijk updated.
2024-09-01 03:35:18.294 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Binnen] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.294 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Regenmeter] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.294 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Slaapkamer Oostzijde] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.294 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Buiten - oost] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.294 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Eetkamer/Keuken] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.294 Status: NetAtmoWeerEnLuchtkwaliteit: HomeStatus parsed
2024-09-01 03:35:18.505 Status: NetAtmoWeerEnLuchtkwaliteit: Events Data parsed

2024-09-01 03:35:18.765 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Binnen] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.765 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Regenmeter] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.765 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Slaapkamer Oostzijde] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.765 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Buiten - oost] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.765 Error: NetAtmoWeerEnLuchtkwaliteit: cloud data for module [Eetkamer/Keuken] no longer updated (module possibly disconnected)
2024-09-01 03:35:18.765 Status: NetAtmoWeerEnLuchtkwaliteit: HomeStatus parsed
2024-09-01 03:35:18.989 Status: NetAtmoWeerEnLuchtkwaliteit: Events Data parsed
2024-09-01 03:35:18.989 Status: NetAtmoWeerEnLuchtkwaliteit: Status 1
```

Note the error messages on each inquiry. 

I did not have the time to investigate (too deep in the night), but I'll take a look at this today.

**Comment by JurgenLB** [comment]
I think you must look at unused devices because my changes use `updatevalueint` they chow up as new devices.

I can't keep the old ID because the old uses a coversion to HEX PRIu64 and the new code only support INT

kind regards

**Comment by JurgenLB** [comment]
But looking at the message in the log, it shows that the cloud data is not live.
this is from line `Log(LOG_ERROR, "cloud data for module [%s] no longer updated (module possibly disconnected)"`
this is 2 times in the code. but maybe that part is not correct.
on my setup I din't have this message.

**Comment by LoukKamp** [comment]
Yeh, I just found the same thing while scanning your changes; I'll put some debug line in there to see why.

But also found another issue (although I don't think this has anything to do with the cloud data messages. At line 924, I think you forgot the call to the POST function:

`//// Missing line???: bRet = HTTPClient::POST("https://api.netatmo.com/api/setthermmode", sPostData, ExtraHeaders, sResult))
`

One other thing I found before, and discussed this with GizmCuz (but didn't get a response yet). At line 1137:
```
		////!!!! The following line will probably crash Domoticz with a stack corruption:
		////!!!! (The response is not expected to have more than one level!
		////!!!! When using a multi-dimensional array, the number of dimensions should be checked first!
		Log(LOG_ERROR, "Error: %s", root["error"]["message"].asString().c_str());

``` 
I can't reproduce this, but I think we need to check on the number of levels of the JSON message before referring to this second level anyway. Maybe more true, now it is used in a commonly used function (Get_Respons_API). What do you think?

Maybe you can think of a test case to produce this message?

**Comment by JurgenLB** [comment]
I'm not sure where you want another POST, line 924;
image

I have tried to put everything in a commonly used function (Get_Respons_API)
so normally there is no POST necessary I think.

By looking at the JSON output, I found that `root["time_utc"]` is not present in Homestatus possible this can be changed to `module["last_seen"]`
but this is not present for every device ?


For the ERROR message, I think `Log(LOG_ERROR, "Error: %s", root["error"].asString().c_str());` is enough 

because the Error message from Netatmo not always include "Message"
I found different error's in the documentation;

The syntax of authentification related error respects the Oauth2 RFC and is as below:

`
{ 
    "error": "Request error type", 
    "error_description": "Request error desc" 
 }`

`{
    "error": { 
        "code": int, 
        "message": "string"     //optional  
    }
 } `

also possible

`{
   "errors":[ 
      { 
         "code":int,
         "id":"device_id"
      }
   ]
}`

**Comment by LoukKamp** [comment]
Ok, That was not the right line number; should be 852:
`
		////Missing line?: bRet = HTTPClient::POST("https://api.netatmo.com/api/setthermmode", sPostData, ExtraHeaders, sResult)
`

I noticed that you changed the URL for the api portal from api.natatmo.net to api.netatmo.com. Although they have the same IP address according to the DNS, I think the official name is api.natatmo.net. However, I couldn't find the source I used, but I found an example in their own documentation where they used .com as well: I'm confused... 

Also found a little language thing:

` 2024-09-01 19:26:41.564 Error: NetAtmoWeerEnLuchtkwaliteit: Error Application does not have the **good** scope rights
` 
I'm not an Englishman, but I think this should be the "appropriate", "proper", or just "right"

In the meanwhile, I'm still testing the time issue. I thought it could be fixed by initialize the variable _tNetatmoLastUpdate_ to the current time. But I just got an alert that there was no communication for more than an hour. So the last update time is not updated somehow.

About the right solution for the formatting of return codes, I will look at that later.

**Comment by JurgenLB** [comment]
No there is no need for a extra POST there;
image

bRet is locally given to Get_Respons_API and then it comes back to use locally.

That ERROR you mention `Error Application does not have the ...`
I don't find that in domoticz so that is something else. Maybe even from Netatmo.


Kind Regards

**Comment by LoukKamp** [comment]
O, sorry: I overlooked line 848. But still don't understand: bRet is a boolean and passed to Get_Response_API by value, so read only. My question is: Where is bRet set?

The message is generated by log function in Netatmo.cpp (based on the lead in of the text); maybe this is a text from a response object...

**Comment by JurgenLB** [comment]
> O, sorry: I overlooked line 848. But still don't understand: bRet is a boolean and passed to Get_Response_API by value, so read only. My question is: Where is bRet set?
> 
> The message is generated by log function in Netatmo.cpp (based on the lead in of the text); maybe this is a text from a response object...

bRet is set on line 842.

For the Message
Yes that is what I meant from Netatmo Response Object.

**Comment by JurgenLB** [comment]
I changed the URL for the api portal from api.natatmo.net to api.netatmo.com because off the documentation.
I found an old script that also uses 'api.natatmo.net' so that is changed true the years

**Comment by LoukKamp** [comment]
I'm not a C++ guru, but what I learned from C and C#, when a function parameter also needs to be an output parameter, it should be a pointer (call by reference). I looked at the definition and the parameter is indeed preceded by an ampersand (&). However, in the call to this function it is not passed as an address, but as a value (no ampersand character). I think this is wrong.

Correction: I seemed to mixed up "call by reference" from C and C++: In C you needed to add the ampersand in the call and an Asterix sign(*) in the function definition. In C++ this is now called "call by pointer". So sorry about wasting your time...

**Comment by LoukKamp** [comment]
> I changed the URL for the api portal from api.netatmo.net to api.netatmo.com because off the documentation. I found an old script that also uses 'api.netatmo.net' so that is changed true the years

We better use the .com variant in that case, I think

**Comment by LoukKamp** [comment]
And yes: The message about the "not good scope" came from _Get_Respons_API()_:

`
        Log(LOG_ERROR, "Error %s", root["error"]["message"].asString().c_str());
` 

So the message was "Application does not have the good scope rights"

The question now is why is this response returned to me, and why only once? And why does it return valid data to me when I don't have good scopes?

I have only one device and defined only one scope at API login: Read_Station (Weather Station)

**Comment by JurgenLB** [comment]
You said that you leave the returnURI on dev.netatmo.com empty.

I suspect that is something to do with it, because from the documentation this need to be filled.
And also the accept button do you see that page? I don't

Kind regards

**Comment by JurgenLB** [comment]
Is this still the same setup or did you make a new one?

Are you still using the same credentials ?

**Comment by LoukKamp** [comment]
> You said that you leave the returnURI on dev.netatmo.com empty.
> 
> I suspect that is something to do with it, because from the documentation this need to be filled. And also the accept button do you see that page? I don't
> 
> Kind regards

This depends on what documentation you read: I think you refer to the Domoticz WIKI page for Netatmo. However, in the Netatmo API documentation it states that it is optional, but when filled in, it should match the redirect URI in the authorization messages (a form of extra security?).

But I wonder what you mean with "It has something to do with it"; with what specific? Doesn't it work for you? In that case, can you be more specific about the problems you experience?

> Is this still the same setup or did you make a new one?
> Are you still using the same credentials ?
> 
I use the same setup (client ID, client secret, and scope) for both situations: Production, testing with my oAuth2 changes, and testing with your API rework changes. Then only thing I change, is the Domoticz image file (rebuild this with make and different sources).

When I use the current beta (including my oAuth2 changes), It all works fine (except for the battery levels, of course). When I replace hardware/Netatmo.cpp and ~.h with the one containing your changes, and rebuild Domoticz, then I ran into the issue with the last update time stamps. When I added a change to ignore this check (by using the current time and date to compare with), I  see data coming in from Netatmo. I'm not sure that this data is stored properly (still busy with checking), but the communication with the Netatmo API portal seems to work OK. Except for that message about not using the good scope; this will need some more investigation.

I hope to find the time to complete my testing of these issues today.

**Comment by LoukKamp** [comment]
The message with the incorrect scope comes from:

```
2024-09-02 17:48:29.924 Status: NetAtmoWeerEnLuchtkwaliteit: Get_Respons_API message returned from POST(https://api.netatmo.com/api/gethomecoachsdata?&get_favorites=true&):
2024-09-02 17:48:29.924 {
2024-09-02 17:48:29.924 . "error" :
2024-09-02 17:48:29.924 . {
2024-09-02 17:48:29.924 . . "code" : 13,
2024-09-02 17:48:29.924 . . "message" : "Application does not have the good scope rights"
2024-09-02 17:48:29.924 . }
2024-09-02 17:48:29.924 }

```

**Comment by JurgenLB** [comment]
I have included the text device with the MAC-adres so the user can see to what device it is referring to.
When dealing with a lot of devices it is difficult to identify the device.


At this moment the 3 groups run always together, but this is a problem in your case
 so I have to make a check on the scopes to start a group.

But can you check the login because in new systems the login is not working
[https://github.com/domoticz/domoticz/issues/6151](url)

**Comment by JurgenLB** [comment]
can you try this change from line 83
`        

        m_bPollThermostat = true;

        if(m_scopes.find("read_station") != std::string::npos)
                m_bPollWeatherData = true;
        else
                m_bPollWeatherData = false;

        if(m_scopes.find("read_homecoach") != std::string::npos) 
                m_bPollHomecoachData = true;
        else
                m_bPollHomecoachData = false;

        m_bPollHomeStatus = true;`

**Comment by LoukKamp** [comment]
I assume that the following lines should be deleted

```
      m_bPollWeatherData = true;
      m_bPollHomecoachData = true;

```

So the patch would look like:

```
@@ -81,9 +81,19 @@ CNetatmo::CNetatmo(const int ID, const std::string& username, const std::string&
        m_ActHome = 0;

        m_bPollThermostat = true;
-       m_bPollWeatherData = true;
-       m_bPollHomecoachData = true;
+
+       if(m_scopes.find("read_station") != std::string::npos)
+               m_bPollWeatherData = true;
+       else
+               m_bPollWeatherData = false;
+
+       if(m_scopes.find("read_homecoach") != std::string::npos)
+               m_bPollHomecoachData = true;
+       else
+               m_bPollHomecoachData = false;
+
        m_bPollHomeStatus = true;
+`      m_bPollThermostat = true;
        m_bPollHome = true;
        m_bFirstTimeThermostat = true;
        m_bFirstTimeWeatherData = true;

```

**Comment by JurgenLB** [comment]
Correct, the 2 lines need to be removed

**Comment by JurgenLB** [comment]
Also on init I think it must set to false

And in GetWeatherDetails remove the last line m_bPollWeatherData = false

And last in GetHomecoachDetails

remove the last line
m_bPollHomecoachData = true

Sorry I dit not think about this situation

**Comment by JurgenLB** [comment]
For reference I have the Old update function standing in comment,
so if you comment this out you get the Old HEX id back but then there is not always a RF-level and other inconsistency

If we use both ways at the same time I think there can be some trouble with the database and the app resources.

But maybe we must put a switch to let the user choose the Old HEX or the New INT

**Pull request merged**
